---
# defaults file for oc-cluster-up

service_catalog: "true"

hawkular_metrics: "false"

host_config_dir: "{{playbook_dir}}/../ui"

cluster_image: openshift/origin

cluster_version: "v3.7.0-rc.0"

cluster_public_hostname: "192.168.37.1"
